### ISSUE TITLE
No Support for Mac OSX

### ISSUE THREAD

**Issue by hcorion** [fowlmouth/nimrod-chipmunk#3]
Hi, It would be great if you could add support for Mac. I assume it would just be the .dylib you'd be searching for rather than .so or .dll

**Comment by matkuki** [comment]
Hi @hcorion,
What's the full name of the library on Mac? `libchipmunk.dylib`?

BTW, there is also a wrapper for Chipmunk7 which supports Mac already, but it's not in the standard library:
https://github.com/BlaXpirit/nim-chipmunk

**Comment by matkuki** [comment]
Added Mac support, open an issue if the Mac dynamic library name is wrong.
